import type { Candidate, SearchQuery } from "../types.ts";
import { type Provider, ProviderError } from "./types.ts";

const BASE="https://www.glcollect.com";
function clean(s:string){return s.replace(/&amp;/g,"&").replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function field(block:string,label:string){const m=block.match(new RegExp(`${label}\\s*:?\\s*(?:<[^>]+>\\s*)*([^<\\n]+)`,`i`));return m?clean(m[1]):null;}
function title(block:string){const candidates=[...block.matchAll(/<(?:h2|h3|h4|a)[^>]*>([\s\S]*?)<\/(?:h2|h3|h4|a)>/gi)].map(m=>clean(m[1])).filter(v=>v&&v.length>8&&!/quick view|wishlist|sale/i.test(v));return candidates.sort((a,b)=>b.length-a.length)[0]??null;}
function href(block:string){const m=block.match(/href=["']([^"']+)["']/i);if(!m)return null;try{return new URL(m[1],BASE).href;}catch{return null;}}
function parse(html:string,query:string):Candidate[]{const chunks=html.split(/(?=SKU\s*:|class=["'][^"']*product)/i);const q=query.toLowerCase();const out:Candidate[]=[];for(const block of chunks){const sku=field(block,"SKU");const name=title(block);if(!sku||!name)continue;const hay=`${sku} ${name}`.toLowerCase();if(q&&!q.split(/\s+/).filter(Boolean).some(t=>hay.includes(t)))continue;const manufacturer=field(block,"Manufacturer");const year=field(block,"Model Year");const scale=field(block,"Scale");const series=field(block,"Series Name");const seriesNo=field(block,"Series #");const n=year?Number.parseInt(year,10):NaN;out.push({id:`greenlight:${sku}`,provider:"greenlight-live",providerLabel:"GreenLight Collectibles",providerKey:sku,title:name,subtitle:[sku,scale,series].filter(Boolean).join(" • ")||null,category:"toy",year:Number.isFinite(n)&&n>0?n:null,imageUrl:null,description:null,sourceUrl:href(block)??`${BASE}/`,details:[{label:"SKU",value:sku},...(manufacturer?[{label:"Manufacturer",value:manufacturer}]:[]),...(scale?[{label:"Scale",value:scale}]:[]),...(series?[{label:"Series",value:series}]:[]),...(seriesNo&&seriesNo!=="-"?[{label:"Series #",value:seriesNo}]:[]),{label:"Source",value:"GreenLight Collectibles official catalog"}],score:80,matchReasons:["Official GreenLight catalog match"]});if(out.length>=24)break;}return out;}
export const greenLightProvider:Provider={id:"greenlight-live",label:"GreenLight Collectibles",categories:["toy"],prefers:q=>q.category==="toy",async search(query:SearchQuery,signal){const term=(query.title||query.providerQuery||query.raw).replace(/\bgreen\s*light\b/gi,"").trim();if(!term)return{candidates:[],warning:"Enter a GreenLight model name or SKU."};const urls=[`${BASE}/search?q=${encodeURIComponent(term)}`,`${BASE}/collections/greenlight-pre-order`,`${BASE}/collections/greenlight-sold-out`];let all:Candidate[]=[];for(const url of urls){try{const r=await fetch(url,{signal,headers:{Accept:"text/html"}});if(!r.ok)continue;all.push(...parse(await r.text(),term));if(all.length>=12)break;}catch(e){if(signal.aborted)throw e;}}const unique=[...new Map(all.map(x=>[x.providerKey,x])).values()];if(!unique.length)throw new ProviderError("No matching GreenLight models were returned by the official catalog.");return{candidates:unique,warning:"GreenLight results are identified live from the official public catalog. Shelfie saves selected factual product metadata only; GreenLight product photography is not copied."};}};
