import type { Candidate, Category, SearchQuery } from "../types.ts";
import type { FigureLine, TcgGame } from "../session.ts";
import { getSearchSelection } from "../search-selection.ts";
import { rankCandidates, type ScoredCandidate } from "../match.ts";
import { amiiboProvider } from "./amiibo.ts";import { cardListsProvider } from "./cardlists.ts";import { fabProvider } from "./fab.ts";import { funkoProvider } from "./funko.ts";import { gcdProvider } from "./gcd.ts";import { lorcanaJsonProvider } from "./lorcanajson.ts";import { onePieceProvider } from "./onepiece.ts";import { openLibraryProvider } from "./openlibrary.ts";import { pokemonProvider } from "./pokemon.ts";import { scryfallProvider } from "./scryfall.ts";import { wikipediaProvider } from "./wikipedia.ts";import { ygoprodeckProvider } from "./ygoprodeck.ts";import { ProviderError,type Provider } from "./types.ts";
export const PROVIDERS:Provider[]=[amiiboProvider,cardListsProvider,gcdProvider,scryfallProvider,ygoprodeckProvider,lorcanaJsonProvider,fabProvider,pokemonProvider,onePieceProvider,funkoProvider,wikipediaProvider,openLibraryProvider];export interface SearchOutcome{results:ScoredCandidate[];warnings:string[];error:string|null;}
function providersFor(category:Category,tcgGame:TcgGame|null,figureLine:FigureLine|null,providers:Provider[]):Provider[]{const cp=providers.filter((p)=>p.categories.includes(category));if(category==="comic")return cp.filter((p)=>p.id==="gcd");if(category==="book")return cp.filter((p)=>p.id==="openlibrary");if(category==="video-game"||category==="sneaker")return cp.filter((p)=>p.id==="wikipedia");if(category==="figure"){const id=figureLine==="funko-pop"?"funko-data":figureLine==="amiibo"?"amiiboapi":"wikipedia";return cp.filter((p)=>p.id===id);}if(category!=="tcg")return cp;const id=tcgGame==="magic"?"scryfall":tcgGame==="yugioh"?"ygoprodeck":tcgGame==="lorcana"?"lorcanajson":tcgGame==="fab"?"fab":tcgGame==="pokemon"?"pokemon-data":tcgGame==="one-piece"?"onepiece-data":null;return id?cp.filter((p)=>p.id===id):[];}
const FIGURE_TERM:Record<FigureLine,string>={amiibo:"amiibo",mcfarlane:"McFarlane Toys","funko-pop":"Funko Pop",nendoroid:"Nendoroid",other:"collectible figure"};
export async function searchAll(query:SearchQuery,categoryOrSignal:Category|AbortSignal,maybeSignal?:AbortSignal,tcgGameArg:TcgGame|null=null,providers:Provider[]=PROVIDERS):Promise<SearchOutcome>{const ui=getSearchSelection();const legacy=categoryOrSignal instanceof AbortSignal;const category=legacy?ui.category:categoryOrSignal;const signal=legacy?categoryOrSignal:maybeSignal as AbortSignal;const tcgGame=legacy?ui.tcgGame:tcgGameArg;const figureLine=ui.figureLine;if(!category)return{results:[],warnings:[],error:"Choose a type first. Select what you're adding to your Shelfie so we know where to search."};if(category==="tcg"&&!tcgGame)return{results:[],warnings:[],error:"Choose a TCG first so Shelfie only searches the right card catalog."};if(category==="figure"&&!figureLine)return{results:[],warnings:[],error:"Choose a figure type first: Amiibo, McFarlane, Funko Pop, Nendoroid, or Other."};const selected=providersFor(category,tcgGame,figureLine,providers);if(!selected.length)return{results:[],warnings:[],error:`No lookup provider is configured for ${category}.`};let typed={...query,category};if(category==="sneaker")typed={...typed,providerQuery:`${query.providerQuery} sneaker`.trim()};if(category==="figure"&&figureLine&&figureLine!=="funko-pop"&&figureLine!=="amiibo"){const brand=FIGURE_TERM[figureLine];typed={...typed,providerQuery:`${brand} ${query.providerQuery}`.trim(),title:`${brand} ${query.title}`.trim()};}const settled=await Promise.allSettled(selected.map((p)=>p.search(typed,signal)));if(signal.aborted)return{results:[],warnings:[],error:null};const collected:Candidate[]=[],warnings:string[]=[],failures:string[]=[];settled.forEach((o,i)=>{const p=selected[i];if(o.status==="fulfilled"){collected.push(...o.value.candidates);if(o.value.warning)warnings.push(`${p.label}: ${o.value.warning}`);}else{const r=o.reason;failures.push(`${p.label}: ${r instanceof ProviderError?r.message:r instanceof Error?r.message:"Lookup service unavailable."}`);}});const error=failures.length===selected.length?failures.join(" "):null;if(failures.length&&!error)warnings.push(...failures);return{results:rankCandidates(typed,collected),warnings,error};}
