import { el } from "./dom.ts";

const CONTACT_EMAIL = "getshelfiecollect@gmail.com";
const MIT_NOTICE = `MIT License\n\nCopyright (c) 2025 JunkWaxData\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`;
const SOURCES = [
  { name:"Wikipedia", text:"Video game lookup currently uses Wikipedia's public API with no account or API key. Article text is available under CC BY-SA 4.0 unless otherwise noted. Images can have separate licenses or fair-use terms; Shelfie links records back to the source article and does not claim ownership of game artwork or trademarks.", url:"https://www.wikipedia.org" },
  { name:"Open Library", text:"Book search metadata and cover links may be supplied by Open Library, an Internet Archive project. Shelfie links records back to Open Library and does not imply affiliation or endorsement. Book cover artwork and other third-party content remain subject to their respective rights.", url:"https://openlibrary.org" },
  { name:"Grand Comics Database", text:"Comic metadata may be provided by the Grand Comics Database under CC BY-SA 4.0. Shelfie attributes GCD and makes adapted GCD metadata available under the same license. Cover artwork is not licensed by GCD under CC BY-SA and remains the property of its respective rights holders.", url:"https://www.comics.org" },
  { name:"CardLists / JunkWaxData", text:"Sports-card checklist data may be provided by CardLists under the MIT License.", url:"https://github.com/robert-porter/CardLists", license:true },
  { name:"Scryfall", text:"Magic: The Gathering lookup data and card imagery may be supplied by Scryfall. Shelfie is not affiliated with or endorsed by Scryfall or Wizards of the Coast.", url:"https://scryfall.com" },
  { name:"YGOPRODeck", text:"Yu-Gi-Oh! lookup data and imagery may be supplied by the YGOPRODeck public API. Yu-Gi-Oh! intellectual property remains with its respective rights holders.", url:"https://ygoprodeck.com" },
  { name:"LorcanaJSON", text:"Disney Lorcana catalog data may be supplied by the community LorcanaJSON project. Shelfie is not affiliated with Disney or Ravensburger.", url:"https://lorcanajson.org" },
  { name:"Flesh and Blood Cards", text:"Flesh and Blood catalog data may be supplied by the community-maintained flesh-and-blood-cards dataset. Shelfie is not affiliated with Legend Story Studios.", url:"https://github.com/the-fab-cube/flesh-and-blood-cards" },
  { name:"Pokémon TCG Data", text:"Pokémon records may be supplied by the PokémonTCG/pokemon-tcg-data historical compatibility dataset. It may not contain the newest releases. Pokémon intellectual property remains with its respective rights holders.", url:"https://github.com/PokemonTCG/pokemon-tcg-data" },
  { name:"Punk Records / One Piece TCG data", text:"One Piece Card Game metadata may be supplied by the OPTCG community dataset. Its software licensing is distinct from underlying card content, which remains with Bandai and other respective rights holders.", url:"https://github.com/Kuroro1990/OPTCG" },
];

function ensureFooterStyles():void{if(document.querySelector("#shelfie-footer-styles"))return;const style=document.createElement("style");style.id="shelfie-footer-styles";style.textContent=`.cs-footer{display:flex;justify-content:center;align-items:center;gap:10px;flex-wrap:wrap;margin:8px auto 28px;padding:18px 16px 0;border-top:1px solid var(--cs-border,#2a3140);max-width:760px;color:var(--cs-muted,#98a2b3);font-size:13px}.cs-footer__link{appearance:none;background:none;border:0;color:inherit;cursor:pointer;font:inherit;padding:6px 2px;text-decoration:none}.cs-footer__link:hover,.cs-footer__link:focus-visible{color:var(--cs-accent,#f5a524);text-decoration:underline}.cs-footer__dot{opacity:.55}.cs-info-dialog{width:min(680px,calc(100vw - 32px));max-height:82vh;padding:0;border:1px solid #2a3140;border-radius:14px;background:#161a22;color:#f2efe6;box-shadow:0 24px 70px rgba(0,0,0,.55)}.cs-info-dialog::backdrop{background:rgba(0,0,0,.7)}.cs-info-dialog__body{padding:22px;line-height:1.5}.cs-info-dialog__head{display:flex;align-items:center;justify-content:space-between;gap:16px}.cs-info-dialog__title{margin:0;font-size:22px}.cs-info-dialog__subtitle{margin:22px 0 6px}.cs-info-dialog__close{border:1px solid #5a667e;border-radius:9px;background:#1e2430;color:#f2efe6;padding:8px 12px;cursor:pointer}.cs-info-dialog a{color:#f5a524}.cs-license{margin-top:18px;padding:14px;border-radius:9px;background:#0c0e13;white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;color:#cbd2df}.cs-attribution{padding:14px 0;border-bottom:1px solid #2a3140}.cs-attribution:last-child{border-bottom:0}.cs-attribution p{margin:6px 0}`;document.head.append(style);}
function infoDialog(title:string,children:HTMLElement[]):HTMLDialogElement{const dialog=el("dialog",{class:"cs-info-dialog"},[el("div",{class:"cs-info-dialog__body"},[el("div",{class:"cs-info-dialog__head"},[el("h2",{class:"cs-info-dialog__title",text:title}),el("button",{class:"cs-info-dialog__close",text:"Close",attrs:{type:"button","aria-label":`Close ${title}`},on:{click:()=>dialog.close()}})]),...children])]) as HTMLDialogElement;dialog.addEventListener("click",(event)=>{if(event.target===dialog)dialog.close();});document.body.append(dialog);dialog.addEventListener("close",()=>dialog.remove(),{once:true});return dialog;}
export function renderFooter():HTMLElement{ensureFooterStyles();const openAbout=():void=>infoDialog("About Shelfie",[el("p",{text:"Shelfie is a simple place to log, organize, and enjoy the collectibles you already own."}),el("p",{text:"Search for an item, confirm the right match, add your own collection details, and keep everything organized on your Shelfie."})]).showModal();const openAttribution=():void=>{const sections=SOURCES.map((source)=>el("section",{class:"cs-attribution"},[el("h3",{class:"cs-info-dialog__subtitle",text:source.name}),el("p",{text:source.text}),el("a",{text:`View ${source.name} source`,attrs:{href:source.url,target:"_blank",rel:"noopener noreferrer"}}),...(source.license?[el("pre",{class:"cs-license",text:MIT_NOTICE})]:[])]));infoDialog("Attribution",[el("p",{text:"Shelfie uses open data and services to help identify collectibles. Source projects and applicable notices are listed below."}),...sections]).showModal();};return el("footer",{class:"cs-footer",attrs:{"aria-label":"Shelfie information"}},[el("a",{class:"cs-footer__link",text:"Contact Us",attrs:{href:`mailto:${CONTACT_EMAIL}?subject=Shelfie%20feedback`}}),el("span",{class:"cs-footer__dot",text:"·",attrs:{"aria-hidden":"true"}}),el("button",{class:"cs-footer__link",text:"About",attrs:{type:"button"},on:{click:openAbout}}),el("span",{class:"cs-footer__dot",text:"·",attrs:{"aria-hidden":"true"}}),el("button",{class:"cs-footer__link",text:"Attribution",attrs:{type:"button"},on:{click:openAttribution}})]);}
