import { CATEGORY_FILTER_LABELS, CATEGORIES, type Category } from "./types.ts";
import type { FigureLine, TcgGame, ToyLine } from "./session.ts";

let category:Category|null=null;let tcgGame:TcgGame|null=null;let figureLine:FigureLine|null=null;let toyLine:ToyLine|null=null;
export function getSearchSelection():{category:Category|null;tcgGame:TcgGame|null;figureLine:FigureLine|null;toyLine:ToyLine|null}{return{category,tcgGame,figureLine,toyLine};}
const GAMES:{value:TcgGame;label:string}[]=[{value:"magic",label:"Magic: The Gathering"},{value:"yugioh",label:"Yu-Gi-Oh!"},{value:"pokemon",label:"Pokémon"},{value:"lorcana",label:"Lorcana"},{value:"one-piece",label:"One Piece"},{value:"fab",label:"Flesh and Blood"},{value:"other",label:"Other"}];
const FIGURES:{value:FigureLine;label:string}[]=[{value:"amiibo",label:"Amiibo"},{value:"mcfarlane",label:"McFarlane"},{value:"funko-pop",label:"Funko Pop"},{value:"nendoroid",label:"Nendoroid"},{value:"other",label:"Other"}];
const TOYS:{value:ToyLine;label:string}[]=[{value:"lego",label:"LEGO"},{value:"transformers",label:"Transformers"},{value:"die-cast",label:"Die-Cast"}];
function button(label:string,pressed:boolean,onClick:()=>void):HTMLButtonElement{const node=document.createElement("button");node.type="button";node.className="cs-chip";node.textContent=label;node.setAttribute("aria-pressed",String(pressed));node.addEventListener("click",onClick);return node;}
function section(title:string):{root:HTMLElement;chips:HTMLElement}{const root=document.createElement("div");root.className="cs-section cs-search-selection";const heading=document.createElement("h3");heading.className="cs-section__title";heading.textContent=title;const chips=document.createElement("div");chips.className="cs-chips";chips.setAttribute("role","group");root.append(heading,chips);return{root,chips};}
export function enhanceSearchSelection(root:HTMLElement):void{const form=root.querySelector<HTMLFormElement>('form[role="search"]');if(!form||root.querySelector("[data-shelfie-search-selection]"))return;const legacy=form.nextElementSibling;if(legacy?.classList.contains("cs-chips"))legacy.remove();const type=section("Choose a type");type.root.dataset.shelfieSearchSelection="true";type.chips.setAttribute("aria-label","Collectible type");for(const value of CATEGORIES){type.chips.append(button(CATEGORY_FILTER_LABELS[value],category===value,()=>{category=value;if(value!=="tcg")tcgGame=null;if(value!=="figure")figureLine=null;if(value!=="toy")toyLine=null;enhanceRefresh(root);}));}form.insertAdjacentElement("afterend",type.root);if(category==="tcg"){const game=section("Choose a TCG");game.root.dataset.shelfieTcgSelection="true";for(const item of GAMES)game.chips.append(button(item.label,tcgGame===item.value,()=>{tcgGame=item.value;enhanceRefresh(root);}));type.root.insertAdjacentElement("afterend",game.root);}else if(category==="figure"){const line=section("Choose a figure type");line.root.dataset.shelfieFigureSelection="true";line.chips.setAttribute("aria-label","Figure type");for(const item of FIGURES)line.chips.append(button(item.label,figureLine===item.value,()=>{figureLine=item.value;enhanceRefresh(root);}));type.root.insertAdjacentElement("afterend",line.root);}else if(category==="toy"){const line=section("Choose a toy type");line.root.dataset.shelfieToySelection="true";line.chips.setAttribute("aria-label","Toy type");for(const item of TOYS)line.chips.append(button(item.label,toyLine===item.value,()=>{toyLine=item.value;enhanceRefresh(root);}));type.root.insertAdjacentElement("afterend",line.root);}}
function enhanceRefresh(root:HTMLElement):void{root.querySelectorAll("[data-shelfie-search-selection],[data-shelfie-tcg-selection],[data-shelfie-figure-selection],[data-shelfie-toy-selection]").forEach((node)=>node.remove());enhanceSearchSelection(root);}
export function clearSearchSelection():void{category=null;tcgGame=null;figureLine=null;toyLine=null;}
